### ISSUE TITLE
In Edit mode, unchecking checkbox on section 7 of initial form does not clear row's other inputs.

### ISSUE THREAD

**Issue by jsibley** [esaude/mental-health#42]
Seems to only happen in Edit mode.

**Comment by kml27** [comment]
Should be fixed by https://github.com/kml27/mental-health-mockup/commit/dd53e158eb0498c620b59976f1b56d9d7f77809f

**Comment by ccwhite333** [comment]
the value shows up after edit mode - but when I hit save after making changes I get the image pasted in here
<img width="1266" alt="screen shot 2018-09-19 at 4 59 38 pm" src="https://user-images.githubusercontent.com/15679308/45788133-8ffbe380-bc2d-11e8-9094-517e54cf415b.png">

**Comment by kml27** [comment]
This issue is about the immediate clearing of disabled elements when unchecking a given element (e.g. clicking depressive disorder on section 7 and setting date, then clicking the checkbox again, should disable and clear the date field.) I believe you meant to add this to #45 based on your slack messages.

**Comment by jsibley** [comment]
Seems to be working now.
